################
### MONITORS ###
################

# [TR] OTOMATİK MONİTÖR YAPILANDIRMASI:
# Herhangi bir monitörü otomatik algılar ve en yüksek yenileme hızında çalıştırır.
# [EN] AUTOMATIC MONITOR CONFIGURATION:
# Automatically detects any monitor and runs it at the highest refresh rate.
monitor = DP-1, 1920x1080@270, 1080x0, 1


# [TR] REZERV ALAN (Waybar vb. için üstten boşluk bırakır):
# Buradaki 'DP-1' kısmını kendi ana monitör isminizle değiştirmeyi unutmayın!
# [EN] RESERVED AREA (Adds space at the top for Waybar etc.):
# Don't forget to change 'DP-1' to your own primary monitor name!
monitor = DP-1, addreserved, 45, 0, 0, 0
