#################
### AUTOSTART ###
#################

# 1. Ekran Ölçeklendirme (XWayland için)
xwayland {
  force_zero_scaling = true
}

# 2. Arka Plan Motoru (Sadece SWWW kalsın, hyprpaper'ı sildik/kapattık) 🖼️
exec-once = swww-daemon

# 3. Pano ve Sistem Araçları 📋
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = sleep 3 && waybar

# 4. Güvenlik ve Kimlik Doğrulama 🔐
exec-once = /usr/lib/gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
