
# Görsel ayarların (Buraya dokunmadık, aynen kalıyor)
decoration {
    rounding = 10

    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = true
        ignore_opacity = true
        xray = false
    }

    # YENİ VERSİYON GÖLGE AYARI ✨
    shadow {
        enabled = true
        range = 10
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    
    # Donmayı engellemek için daha güvenli bir ayar:
    vfr = true 
    # Eğer varsa bunu 0 yap (titremeyi engellemek için):
    vrr = 0 
}


misc {
    # Bu iki satır o yazıları sonsuza kadar susturur 🤫
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
